version: 2

sources:
  - name: raw
    database: AB_TEST_DB
    schema: RAW
    tables:
      - name: raw_experiment_events

models:
  - name: stg_experiment_events
    description: 'Cleaned and deduplicated experiment events'
    columns:
      - name: borrower_id
        data_tests: [unique, not_null]
      - name: experiment_group
        data_tests:
          - accepted_values:
              arguments:
                values: ['control', 'treatment']
